FROM --platform=linux/arm64 python:3.10-slim

RUN pip install mlflow && \
    pip install protobuf==3.20.3

EXPOSE 7100

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "7100", \
     "--backend-store-uri", "sqlite:///mlflow.db", \
     "--default-artifact-root", "/mlflow/artifacts"]